services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notebook-api
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=flaskpass
      - MYSQL_DB=notebookdb
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notebook-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: notebook-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notebookdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
